version: 2

formats: 
  - htmlzip

python:
  version: "3.10"
  install:
    - requirements: docs/requirements.txt
    - method: pip
      path: .

sphinx:
  builder: html
  configuration: docs/conf.py
  fail_on_warning: true
