#!/bin/bash

if [[ ! $(pwd) = /home/riccardoob/git_training_folder ]] && [[ ! $(pwd) = /home/riccardoob/delete ]] ; then
	echo "Not in correct folder"
else
	set -x
	git init

	echo 'test content' | git hash-object -w --stdin
	git cat-file -p d670460b4b4aece5915caf5c68d12f560a9fe3e4

	echo 'version 1' > test.txt
	git hash-object -w test.txt

	echo 'version 2' > test.txt
	git hash-object -w test.txt

	git update-index --add --cacheinfo 100644 83baae61804e65cc73a7201a7252750c76066a30 test.txt
	git write-tree
	git cat-file -p d8329fc1cc938780ffdd9f94e0d364e0ea74f579

	echo 'new file' > new.txt
	git update-index --add --cacheinfo 100644 1f7a7a472abf3dd9643fd615f6da379c4acb3e3a test.txt
	git update-index --add new.txt
	git write-tree
	git cat-file -p 0155eb4229851634a0f03eb265b69f5a2d56f341

	git read-tree --prefix=bak d8329fc1cc938780ffdd9f94e0d364e0ea74f579
	git write-tree
	git cat-file -p 3c4e9cd789d88d8d89c1073707c3585e41b0e614

	first_commit=$(echo 'First commit' | git commit-tree d8329f)
	git cat-file -p $first_commit

	second_commit=$(echo 'Second commit' | git commit-tree 0155eb -p $first_commit)
	git cat-file -p $second_commit

	third_commit=$(echo 'Third commit' | git commit-tree 3c4e9c -p $second_commit)
	git cat-file -p $third_commit

	git log --stat $third_commit

















	set +x
fi
