#!/bin/bash

check_path {
    if [ $# -eq 0 ] && [ -d .git ] ; then
	dir=.
    elif [ $# -eq 0 ] && [ ! -d -git ] ; then
        echo "Insert path or cd to a git repository." 1>&2
        exit -1
    elif [ $# -ne 0 ] && [ -d .git ] ; then
        if [ -d $1/.git ] ; then
            echo "$1 and current directory are git repo, using $1"
            dir=$1
        else
            echo "$1 is not a git repository, using current direcory"
            dir=.
        fi
    else
        if [ -d $1/.git ] ; then
            dir=$1
        else
            echo "$1 nor current directory are git repo, insert valid path or cd to a git repository" 1>&2
            exit -2
        fi
    fi
}