#!/bin/bash

if [ $# -eq 0 ] && [ -d .git ] ; then
	dir=.
elif [ $# -eq 0 ] && [ ! -d -git ] ; then
	echo "Insert path or cd to a git repository." 1>&2
	exit -1
elif [ $# -ne 0 ] && [ -d .git ] ; then
	if [ -d $1/.git ] ; then
		echo "$1 and current directory are git repo, using $1"
		dir=$1
	else
		echo "$1 is not a git repository, using current direcory"
		dir=.
	fi
else
	if [ -d $1/.git ] ; then
		dir=$1
	else
		echo "$1 nor current directory are git repo, insert valid path or cd to a git repository" 1>&2
		exit -2
	fi
fi

dir=$(realpath $dir)
cd $dir

echo "Retrieving objects for repository $dir."

hashes_file=/home/riccardoob/git_scripts/hashes
> $hashes_file
for SHA1_2 in $dir/.git/objects/* ; do
    SHA1_2=$(basename $SHA1_2)
    if [[ $SHA1_2 =~ ^[a-z0-9]{2}$ ]] ; then
        for SHA1_38 in $dir/.git/objects/$SHA1_2/* ; do
            SHA1_40=$SHA1_2$(basename $SHA1_38)
            echo "$(git cat-file -t $SHA1_40) $SHA1_40" >> $hashes_file
            echo "$(git cat-file -t $SHA1_40) $SHA1_40"
        done
    fi
done
