#!/bin/bash

get_tree $1 1>/dev/null
if [ $? -ne 0 ] ; then
	exit -1
fi

trees=$(cat /home/riccardoob/git_scripts/trees)

dir=$(realpath $(cat /tmp/temp_dir))
cd $dir

regex="[ ]*tree ([a-z0-9]{40})"

echo "Retrieved tree hashes for $dir, retrieving blob hashes."

blob_file=/home/riccardoob/git_scripts/blob
> $blob_file
while read line ; do
    if [[ $line = *commit* ]] ; then
        continue
    fi

    [[ $line =~ $regex ]]
    tree_SHA1=${BASH_REMATCH[1]}

	echo "tree $tree_SHA1" >> $blob_file
	echo "tree $tree_SHA1"
	tree_lines=$(git ls-tree $tree_SHA1 | grep blob)
	while read tree_line ; do
		SHA1=$(echo $tree_line | cut -d' ' -f3)
		echo -e "\tblob $SHA1" >> $blob_file
		echo -e "\tblob $SHA1"
	done <<< $tree_lines
done <<< $trees
