#!/bin/bash

SESSIONNAME="git_edit_tmux"
tmux has-session -t $SESSIONNAME &> /dev/null

if [ $? != 0 ] ; then
	tmux new-session -s $SESSIONNAME -n main -d
	tmux split-window -h -t $SESSIONNAME
	tmux split-window -h -t $SESSIONNAME
	tmux send-keys -t $SESSIONNAME:main.0 "nano /home/riccardoob/git_scripts/get_commit" Enter
	tmux send-keys -t $SESSIONNAME:main.1 "nano /home/riccardoob/git_scripts/get_tree" Enter
	tmux send-keys -t $SESSIONNAME:main.2 "nano /home/riccardoob/git_scripts/get_blob" Enter

fi

tmux attach -t $SESSIONNAME
